### PR TITLE
add 2 more custom devices intel_gpu and apple mps

### PR DESCRIPTION
**Pull request by KimBioInfoStudio**
in PaddleCustomDevice there are two new types of hw was supported, on is the Intel Data Center GPU and another is Apple MPS, so this pr aims to add those two kind of devices to paddleclas repo and prepare for some benchmark data base on this repo

### CODE REVIEW

**Comment by KimBioInfoStudio** [comment]
@chaofanl  @kevinyuk @qili93 @ronny1996  pls help review

**Review by chaofanl — APPROVED** [review]
LGTM

**Comment by cuicheng01** [comment]
We recommend withdrawing the PR and pushing the changes to the develop branch，thx~

**Comment by KimBioInfoStudio** [comment]
> We recommend withdrawing the PR and pushing the changes to the develop branch，thx~

new pr in https://github.com/PaddlePaddle/PaddleClas/pull/2841

**Pull request closed without merging**
