### PR TITLE
fix RandomErasing not work

### PR DESCRIPTION
**Pull request by nblib**
as title:
RandomErasing should be configured before ToCHWImage,so, modify code

### CODE REVIEW

**Comment by littletomatodonkey** [comment]
Thanks for your attention! Actually the code is same as before. The only difference is the channel order.

**Comment by nblib** [comment]
Yes, it's OK to change the config order, otherwise it won't work:
configs/quick_start/ResNet50_vd_ssld_random_erasing_finetune.yaml
```
- RandomErasing:
        EPSILON: 0.5
- ToCHWImage:
```

**Comment by littletomatodonkey** [comment]
> Yes, it's OK to change the config order, otherwise it won't work:
> configs/quick_start/ResNet50_vd_ssld_random_erasing_finetune.yaml
> 
> ```
> - RandomErasing:
>         EPSILON: 0.5
> - ToCHWImage:
> ```
 Oh you are right, could you please fix the the file `configs/quick_start/ResNet50_vd_ssld_random_erasing_finetune.yaml` and `configs/DataAugment/ResNet50_RandomErasing.yaml`?

**Comment by nblib** [comment]
done

**Review by littletomatodonkey — APPROVED** [review]

**Pull request merged**
